layout_spectrum: 0.9185157
color:
  saturation: 0.5938619
  lightness: 0.7371788
  brandStrength: 0.7484517
  brandColors:
    - '#FAF3E6'
    - '#F2B380'
    - '#1F0D03'
    - '#5C4A3A'
    - '#FF6565'
  rhythmicContrast: 0.7928161
typography_spectrum: 0.1228658
name: 'Tyrone Shoots '
